"""
Funding Rate Arbitrage Strategy Configurations.

Configuration is loaded from heatmap_results.json (generated by --heatmap scan).
Each Mesa region represents a stable profitable parameter plateau, ranked by Sharpe ratio.

Usage:
    from strategy.bitget.funding_rate.configs import get_config

    # Get best Mesa config (index 0)
    config = get_config(0)
    fr_config, filter_config = config.get_configs()

Generate configs by running:
    uv run python -m strategy.backtest -S funding_rate -X bitget --heatmap
"""

from pathlib import Path
from typing import List

from strategy.backtest.config import (  # noqa: F401
    BacktestResultRecord,
    StrategyConfig,
)
from strategy.backtest.config import get_config as _get_config
from strategy.backtest.config import load_mesa_configs as _load_mesa_configs

# Re-export FundingRateFilterConfig for backward compat
from strategy.strategies.funding_rate.signal import FundingRateFilterConfig  # noqa: F401

# Canonical mesa-dict conversion lives in the registration module
from strategy.strategies.funding_rate.registration import _mesa_dict_to_config

# ---------------------------------------------------------------------------
# Mesa config loading from heatmap_results.json
# ---------------------------------------------------------------------------

_RESULTS_PATH = Path(__file__).parent / "heatmap_results.json"


def load_funding_rate_mesa_configs() -> List[StrategyConfig]:
    """Load Mesa configurations from heatmap_results.json."""
    return _load_mesa_configs(_RESULTS_PATH, _mesa_dict_to_config)


# Alias for backward compatibility
load_mesa_configs = load_funding_rate_mesa_configs


def get_funding_rate_config(mesa_index: int = 0) -> StrategyConfig:
    """Get configuration for a specific Mesa (0-indexed, 0 = best)."""
    return _get_config(mesa_index, _RESULTS_PATH, _mesa_dict_to_config)


# Backward-compatible alias
get_config = get_funding_rate_config


def get_recommended_config() -> StrategyConfig:
    """Get the top-ranked Mesa configuration (best Sharpe)."""
    return get_funding_rate_config(0)


def list_all_configs() -> None:
    """Print a summary of all available Mesa configurations."""
    try:
        configs = load_funding_rate_mesa_configs()
    except FileNotFoundError as e:
        print(str(e))
        return

    print("=" * 80)
    print("FUNDING RATE ARBITRAGE MESA CONFIGURATIONS")
    print("=" * 80)
    print(
        f"\n{'#':<4} {'Name':<30} {'Sharpe':>8} {'Stability':>10} "
        f"{'Freq':<25} {'HrsBefore':>10} {'SMA':>6}"
    )
    print("-" * 95)

    for cfg in configs:
        rec = " [BEST]" if cfg.recommended else ""
        print(
            f"{cfg.mesa_index:<4} {cfg.name:<30}{rec:<7} "
            f"{cfg.avg_sharpe:>8.2f} {cfg.stability:>10.2f} "
            f"{cfg.frequency_label:<25} "
            f"{cfg.strategy_config.hours_before_funding:>10} "
            f"{cfg.strategy_config.price_sma_period:>6}"
        )

    print("\n" + "=" * 80)
    print("To use: get_config(0) for best, get_config(1) for second best, etc.")
    print("Re-generate: uv run python -m strategy.backtest -S funding_rate -X bitget --heatmap")
    print("=" * 80)


if __name__ == "__main__":
    list_all_configs()
