"""
EMA Crossover + Regime Filter Strategy Configurations.

Configuration is loaded from heatmap_results.json (generated by --heatmap scan).
Each Mesa region represents a stable profitable parameter plateau, ranked by Sharpe ratio.

Usage:
    from strategy.bitget.regime_ema.configs import get_config

    # Get best Mesa config (index 0)
    config = get_config(0)
    regime_config, filter_config = config.get_configs()

Generate configs by running:
    uv run python -m strategy.backtest -S regime_ema -X bitget --heatmap
"""

from pathlib import Path
from typing import List

from strategy.backtest.config import (  # noqa: F401
    BacktestResultRecord,
    StrategyConfig,
)
from strategy.backtest.config import get_config as _get_config
from strategy.backtest.config import load_mesa_configs as _load_mesa_configs

# Re-export TradeFilterConfig for backward compat (used by strategy.py)
from strategy.strategies.regime_ema.signal import RegimeEMATradeFilterConfig  # noqa: F401

# Canonical mesa-dict conversion lives in the registration module
from strategy.strategies.regime_ema.registration import (
    _mesa_dict_to_config,
)

# ---------------------------------------------------------------------------
# Mesa config loading from heatmap_results.json
# ---------------------------------------------------------------------------

_RESULTS_PATH = Path(__file__).parent / "heatmap_results.json"


def load_regime_ema_mesa_configs() -> List[StrategyConfig]:
    """Load Mesa configurations from heatmap_results.json."""
    return _load_mesa_configs(_RESULTS_PATH, _mesa_dict_to_config)


# Aliases for backward compatibility
load_mesa_configs = load_regime_ema_mesa_configs


def get_regime_ema_config(mesa_index: int = 0) -> StrategyConfig:
    """Get configuration for a specific Mesa (0-indexed, 0 = best)."""
    return _get_config(mesa_index, _RESULTS_PATH, _mesa_dict_to_config)


# Backward-compatible alias (used by strategy.py)
get_config = get_regime_ema_config


def get_recommended_config() -> StrategyConfig:
    """Get the top-ranked Mesa configuration (best Sharpe)."""
    return get_regime_ema_config(0)


def list_all_configs() -> None:
    """Print a summary of all available Mesa configurations."""
    try:
        configs = load_regime_ema_mesa_configs()
    except FileNotFoundError as e:
        print(str(e))
        return

    print("=" * 80)
    print("EMA CROSSOVER + REGIME FILTER MESA CONFIGURATIONS")
    print("=" * 80)
    print(
        f"\n{'#':<4} {'Name':<30} {'Sharpe':>8} {'Stability':>10} "
        f"{'Freq':<25} {'Fast':>6} {'Slow':>6}"
    )
    print("-" * 95)

    for cfg in configs:
        rec = " [BEST]" if cfg.recommended else ""
        print(
            f"{cfg.mesa_index:<4} {cfg.name:<30}{rec:<7} "
            f"{cfg.avg_sharpe:>8.2f} {cfg.stability:>10.2f} "
            f"{cfg.frequency_label:<25} "
            f"{cfg.strategy_config.fast_period:>6} "
            f"{cfg.strategy_config.slow_period:>6}"
        )

    print("\n" + "=" * 80)
    print(
        "To use: get_regime_ema_config(0) for best, get_regime_ema_config(1) for second best, etc."
    )
    print(
        "Re-generate: uv run python -m strategy.backtest -S regime_ema -X bitget --heatmap"
    )
    print("=" * 80)


if __name__ == "__main__":
    list_all_configs()
